using SharpMUSH.Library.ParserInterfaces;

namespace SharpMUSH.Tests.Parser;

/// <summary>
/// Oracle tests extracted from PennMUSH test suite.
/// Each test verifies SharpMUSH produces identical output to PennMUSH
/// for pure function evaluations (no object state required).
/// Source: pennmush/test/*.t files
/// Only exact-match tests included (no regex, no object-state dependencies).
/// </summary>
public class PennMUSHOracleTests
{
	[ClassDataSource<ServerWebAppFactory>(Shared = SharedType.PerTestSession)]
	public required ServerWebAppFactory WebAppFactoryArg { get; init; }

	private IMUSHCodeParser Parser => WebAppFactoryArg.FunctionParser;

	[Test]
	// TODO: Depends on backslash-space escaping behavior (\ → literal space in PennMUSH)
	// [Arguments("decompose.2", "decompose(a\\ \\ \\ \\ b)", "a %b %bb")]
	[Arguments("decompose.3", "decompose(s(tab%treturn%r))", "tab%treturn%r")]
	[Arguments("decompose.4", "decompose(before(ansi(h,x),x)hello)", "hello")]
	[Arguments("digest.1", "digest(md5,foo)", "acbd18db4cc2f85cedef654fccc4a4d8")]
	[Arguments("digest.3", "digest(sha1,foo)", "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33")]
	// Skipped: RIPEMD160 not available in .NET 5+
	// [Arguments("digest.5", "digest(ripemd160,foo)", "42cfa211018ea492fdee45ac637b7972a0ad6873")]
	// Skipped: MD4 not available in .NET
	// [Arguments("digest.6", "digest(md4,foo)", "0ac6700c491d70fb8650940b1ca1e4b2")]
	[Arguments("base64.1", "encode64(test string)", "dGVzdCBzdHJpbmc=")]
	[Arguments("lit.semi", "lit(;)", ";")]
	[Arguments("lit.pct_hash", "lit(%#)", "%#")]
	[Arguments("fn.add", "fn(add,1,2)", "3")]
	[Arguments("fn.error", "fn(notafunction)", "#-1")]
	// Skipped: requires @function myfn setup (object state)
	// [Arguments("atfun.3", "myfn(test)", "CUSTOM-test")]
	// Skipped: requires @function myfn setup (object state)
	// [Arguments("atfun.4", "fn(myfn,test)", "#-1")]
	[Arguments("fn.case", "[fn(ADD,1,2)]", "3")]
	[Arguments("fn.zero_args_add", "[fn(add)]", "#-1 FUNCTION (ADD) EXPECTS AT LEAST 2 ARGUMENTS BUT GOT 0")]
	[Arguments("lit.1", "lit(hello world)", "hello world")]
	[Arguments("lit.2", "lit(%#)", "%#")]
	[Arguments("lit.4", "lit(near       far)", "near       far")]
	[Arguments("lit.5", "lit(%b%b%b)", "%b%b%b")]
	[Arguments("lit.6", "lit({test})", "{test}")]
	[Arguments("compress.1", "hello     world", "hello world")]
	[Arguments("compress.2", "   leading", "leading")]
	[Arguments("compress.3", "trailing   ", "trailing")]
	[Arguments("compress.4", "a  b  c  d", "a b c d")]
	// PE_COMPRESS_SPACES: function output trailing stripped, leading preserved
	[Arguments("cs.fn.1", "[space(5)]hello", "     hello")]
	[Arguments("cs.fn.2", "hello[space(5)]", "hello     ")]
	[Arguments("cs.fn.3", "[ljust(a,10)]end", "a         end")]
	[Arguments("cs.fn.4", "start[rjust(a,10)]", "start         a")]
	[Arguments("cs.fn.5", "[space(3)]x[space(3)]", "   x   ")]
	// PE_COMPRESS_SPACES: function args trimmed both sides
	[Arguments("cs.arg.1", "[strlen(  a  )]", "1")]
	[Arguments("cs.arg.2", "[strlen( a )]", "1")]
	[Arguments("cs.arg.3", "[strlen(a  b)]", "3")]
	[Arguments("cs.arg.4", "[strlen(  a  b  )]", "3")]
	[Arguments("cs.arg.5", "[mid(  hello  ,0,5)]", "hello")]
	[Arguments("cs.arg.6", "[mid(  a  b  ,0,3)]", "a b")]
	// PE_COMPRESS_SPACES: cat with spaced args
	[Arguments("cs.cat.1", "[cat(  a  ,  b  )]", "a b")]
	[Arguments("cs.cat.2", "[cat(  a  b  ,  c  d  )]", "a b c d")]
	// PE_COMPRESS_SPACES: mixed literal + function output
	[Arguments("cs.mix.1", "X  [add(1,2)]  Y", "X 3 Y")]
	[Arguments("cs.mix.2", "[add(1,2)]  text  [add(2,2)]", "3 text 4")]
	// PE_COMPRESS_SPACES: literal spaces between function calls compressed
	[Arguments("cs.between.1", "[add(1,1)]  [add(2,2)]", "2 4")]
	[Arguments("cs.between.2", "[add(1,1)]     [add(2,2)]", "2 4")]
	[Arguments("cs.between.3", "[add(1,1)] [add(2,2)]", "2 4")]
	// PE_COMPRESS_SPACES: bracket-only, trailing stripped
	[Arguments("cs.brk.1", "[space(3)]", "   ")]
	[Arguments("cs.brk.2", "[ljust(a,5)]", "a    ")]
	[Arguments("cs.brk.3", "[rjust(a,5)]", "    a")]
	// PE_COMPRESS_SPACES: edge cases
	[Arguments("cs.edge.1", " ", "")]
	[Arguments("cs.edge.2", "   ", "")]
	// PE_COMPRESS_SPACES: nested functions
	[Arguments("cs.nest.1", "[cat([ljust(a,5)],[rjust(b,5)])]", "a         b")]
	[Arguments("cs.nest.2", "[strlen([space(5)])]", "5")]
	[Arguments("fn.1", "fn(add,1,2)", "3")]
	[Arguments("fn.2", "fn(mul,3,4)", "12")]
	[Arguments("fn.3", "fn(cat,hello,world)", "hello world")]
	[Arguments("userfn.1", "fn(mid,hello,1,3)", "ell")]
	// Skipped: mid-string function recognition — deliberate incompatibility
	// [Arguments("qreg_noparse.1", "[setq(0,test)]lit(%q0)", "%q0")]
	[Arguments("qreg_noparse.2", "[setq(0,test)]%q0", "test")]
	[Arguments("qreg_noparse.3", "lit(%q0)", "%q0")]
	[Arguments("lit_spaces.1", "lit(  hello   world  )", "  hello   world  ")]
	[Arguments("insert.1", "insert(a b c,0,X)", "a b c")]
	[Arguments("insert.2", "insert(a b c,1,X)", "X a b c")]
	[Arguments("insert.3", "insert(a b c,2,X)", "a X b c")]
	[Arguments("insert.4", "insert(a b c,3,X)", "a b X c")]
	[Arguments("insert.5", "insert(a b c,4,X)", "a b c")]
	[Arguments("insert.6", "insert(a b c,-1,X)", "a b c X")]
	[Arguments("insert.7", "insert(a b c,-2,X)", "a b X c")]
	[Arguments("insert.8", "insert(a b c,-3,X)", "a X b c")]
	[Arguments("insert.9", "insert(a b c,-4,X)", "a b c")]
	[Arguments("json.isjson.2", "isjson(foo)", "0")]
	[Arguments("json.null.1", "json(null)", "null")]
	[Arguments("json.null.2", "json(null,null)", "null")]
	[Arguments("json.null.3", "json(null,foo)", "#-1")]
	[Arguments("json.boolean.5", "json(boolean, 5)", "#-1")]
	[Arguments("json.number.1", "json(number, 5)", "5")]
	[Arguments("json.number.2", "json(number, 5.555)", "5.555")]
	[Arguments("json.number.3", "json(number, foo)", "#-1")]
	[Arguments("json.type.1", "json_query(\"foo\", type)", "string")]
	[Arguments("json.type.2", "json_query(1, type)", "number")]
	[Arguments("json.type.3", "json_query(3.14, type)", "number")]
	[Arguments("json.type.4", "json_query(null, type)", "null")]
	[Arguments("json.type.5", "json_query(true, type)", "boolean")]
	[Arguments("json.type.6", "json_query(false, type)", "boolean")]
	[Arguments("json.type.8", "json_query(json(array, 1), type)", "array")]
	[Arguments("json.type.9", "json_query(foo, type)", "#-1")]
	[Arguments("json.size.1", "json_query(null, size)", "0")]
	[Arguments("json.size.2", "json_query(true, size)", "1")]
	[Arguments("json.size.3", "json_query(1, size)", "1")]
	[Arguments("json.size.4", "json_query(1.1, size)", "1")]
	[Arguments("json.size.5", "json_query(\"foo\", size)", "1")]
	[Arguments("json.size.6", "json_query(\\[\\], size)", "0")]
	[Arguments("json.size.7", "json_query(json(array, 1, 2), size)", "2")]
	[Arguments("json.size.8", "json_query(\\{\\}, size)", "0")]
	[Arguments("json.exists.5", "json_query(\"foo\", exists, a)", "#-1")]
	[Arguments("json.exists.6", "json_query(foo, exists, a)", "#-1")]
	[Arguments("json.get.5", "json_query(\"foo\", get, a)", "#-1")]
	[Arguments("json.get.6", "json_query(foo, get, a)", "#-1")]
	[Arguments("json.extract.5", "json_query(\"foo\", extract, $)", "foo")]
	[Arguments("json.extract.6", "json_query(foo, extract, $.a)", "#-1")]
	[Arguments("abs.1", "abs(-1)", "1")]
	[Arguments("abs.2", "abs(-1.5)", "1.5")]
	[Arguments("abs.3", "abs(1)", "1")]
	[Arguments("abs.4", "abs(0)", "0")]
	[Arguments("abs.5", "abs(-0)", "0")]
	[Arguments("abs.6", "abs(99999999999)", "99999999999")]
	[Arguments("abs.7", "abs(-99999999999)", "99999999999")]
	[Arguments("sqrt.1", "sqrt(4)", "2")]
	[Arguments("sqrt.2", "sqrt(-1)", "#-1 IMAGINARY NUMBER")]
	[Arguments("root.1", "root(4,2)", "2")]
	[Arguments("root.2", "root(-1,2)", "#-1 IMAGINARY NUMBER")]
	[Arguments("root.3", "root(27, 3)", "3")]
	[Arguments("root.4", "root(-27, 3)", "-3")]
	[Arguments("root.5", "root(125, 5)", "2.6265278044037674")]
	[Arguments("round.0", "round(pi(), 0)", "3")]
	[Arguments("round.1", "round(pi(), 1)", "3.1")]
	[Arguments("null.1", "null()", "")]
	[Arguments("null.2", "null(a)", "")]
	[Arguments("null.3", "null(a,b,c)", "")]
	[Arguments("rand.1", "rand(-1)", "0")]
	[Arguments("rand.2", "rand(0)", "#-1")]
	[Arguments("rand.3", "rand(1)", "0")]
	[Arguments("rand.5", "rand(0,0)", "0")]
	[Arguments("rand.6", "rand(1,1)", "1")]
	[Arguments("randword.2", "randword(foo)", "foo")]
	[Arguments("reswitch.1", "reswitch(test STRING,t,1,0)", "1")]
	[Arguments("reswitch.2", "reswitch(test STRING,t,1,e,2,0)", "1")]
	[Arguments("reswitch.3", "reswitch(test STRING,E,1,0)", "0")]
	[Arguments("reswitch.4", "reswitch(test STRING,.\\{4\\}\\\\\\s\\[A-Z\\]\\{6\\},9,t,1,E,2,0)", "9")]
	[Arguments("reswitch.5", "reswitchall(test STRING,t,1,0)", "1")]
	[Arguments("reswitch.6", "reswitchall(test STRING,t,1,e,2,0)", "12")]
	[Arguments("reswitch.7", "reswitchall(test STRING,E,1,0)", "0")]
	[Arguments("reswitch.8", "reswitchall(test STRING,.\\{4\\}\\\\\\s\\[A-Z\\]\\{6\\},9,t,1,E,2,0)", "91")]
	[Arguments("reswitch.9", "reswitchi(test STRING,t,1,0)", "1")]
	[Arguments("reswitch.10", "reswitchi(test STRING,t,1,e,2,0)", "1")]
	[Arguments("reswitch.11", "reswitchi(test STRING,E,1,0)", "1")]
	[Arguments("reswitch.12", "reswitchi(test STRING,.\\{4\\}\\\\\\s\\[A-Z\\]\\{6\\},9,t,1,E,2,0)", "9")]
	[Arguments("reswitch.13", "reswitchalli(test STRING,t,1,0)", "1")]
	[Arguments("reswitch.14", "reswitchalli(test STRING,t,1,e,2,0)", "12")]
	[Arguments("reswitch.15", "reswitchalli(test STRING,E,1,0)", "1")]
	[Arguments("reswitch.16", "reswitchalli(test STRING,.\\{4\\}\\\\\\s\\[A-Z\\]\\{6\\},9,t,1,E,2,0)", "912")]
	// TODO: PennMUSH float sort has specific tie-breaking and formatting behavior
	// [Arguments("sort.2", "sort(0.0 0 0.3 *foo*,f)", "0 *foo* 0.3")]
	[Arguments("sort.3", "sort(a [ansi(h,a)] b [ansi(h,b)] c d [ansi(h,e)] f)", "a a b b c d e f")]
	[Arguments("sort.4", "sort(3 [ansi(h,1)] [ansi(y,7)] 5)", "1 3 5 7")]
	[Arguments("soundex.1", "soundex(a)", "A000")]
	[Arguments("soundex.2", "soundex(fred)", "F630")]
	[Arguments("soundex.3", "soundex(phred, soundex)", "F630")]
	[Arguments("soundex.4", "soundex(afford)", "A163")]
	[Arguments("stringsecs.1", "stringsecs(a)", "#-1 INVALID TIMESTRING")]
	[Arguments("stringsecs.2", "stringsecs(10)", "10")]
	[Arguments("stringsecs.3", "stringsecs(10s)", "10")]
	[Arguments("stringsecs.4", "stringsecs(5m)", "300")]
	[Arguments("stringsecs.5", "stringsecs(5m 10s)", "310")]
	[Arguments("stringsecs.6", "stringsecs(1h)", "3600")]
	[Arguments("stringsecs.7", "stringsecs(10s 5m)", "310")]
	[Arguments("stringsecs.8", "stringsecs(1d 2h 3m 4s)", "93784")]
	[Arguments("etimefmt.6", "etimefmt($ts, 75)", "75")]
	[Arguments("etimefmt.7", "etimefmt($xm$xs, 75)", "1m15s")]
	[Arguments("etimefmt.13", "etimefmt($h, -200)", "#-1")]
	[Arguments("etimefmt.14", "etimefmt($h, twelve)", "#-1")]
	[Arguments("etimefmt.15", "etimefmt($2h:$2M, 3700)", " 1:01")]
	[Arguments("etimefmt.16", "etimefmt(You have $m minutes and $s seconds to go, 78)", "You have 1 minutes and 18 seconds to go")]
	[Arguments("timestring.4", "timestring(-50)", "#-1")]
	[Arguments("timestring.5", "timestring(four)", "#-1")]
	[Arguments("stringsecs.1", "stringsecs(5m 1s)", "301")]
	[Arguments("stringsecs.2", "stringsecs(3y 2m 7d 5h 23m)", "95232300")]
	[Arguments("stringsecs.3", "stringsecs(foo)", "#-1")]
	[Arguments("etime.5", "etime(foo)", "#-1")]
	[Arguments("etime.6", "etime(50, foo)", "#-1")]
	[Arguments("trimpenn.1", "trimpenn(XXXfooXXX, X, l)", "fooXXX")]
	[Arguments("trimpenn.2", "trimpenn(XXXfooXXX, X, r)", "XXXfoo")]
	[Arguments("trimpenn.3", "trimpenn(XXXfooXXX, X, b)", "foo")]
	[Arguments("trimpenn.4", "trimpenn(XXXfooXXX, Y, l)", "XXXfooXXX")]
	[Arguments("trimtiny.1", "trimtiny(XXXfooXXX, L, X)", "fooXXX")]
	[Arguments("trimtiny.2", "trimtiny(XXXfooXXX, R, X)", "XXXfoo")]
	[Arguments("trimtiny.3", "trimtiny(XXXfooXXX, B, X)", "foo")]
	[Arguments("trimtiny.4", "trimtiny(XXXfooXXX, l, Y)", "XXXfooXXX")]
	[Arguments("trim.1", "trimtiny(XXXfooXXX, l, X)", "fooXXX")]
	[Arguments("trim.2", "trim(XXXfooXXX, X, l)", "fooXXX")]
	[Arguments("tr.1", "tr(test STRING,,)", "test STRING")]
	[Arguments("tr.2", "tr(test STRING,t,)", "#-1")]
	[Arguments("tr.3", "tr(test STRING,,t)", "#-1")]
	[Arguments("tr.4", "tr(test STRING,t,f)", "fesf STRING")]
	[Arguments("tr.5", "tr(test STRING,tT,fF)", "fesf SFRING")]
	[Arguments("tr.6", "tr(test STRING,Tt,Ff)", "fesf SFRING")]
	[Arguments("tr.7", "tr(test STRING,te,et)", "etse STRING")]
	public async Task OracleTest(string testName, string input, string expected)
	{
		var result = (await Parser.FunctionParse(MModule.single(input)))?.Message?.ToPlainText();
		// PennMUSH tests use regex matching — bare "#-1" means "starts with #-1"
		if (expected == "#-1")
			await Assert.That(result).StartsWith("#-1");
		else
			await Assert.That(result).IsEqualTo(expected);
	}
}
