<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMUSH.Library\SharpMUSH.Library.csproj" />
    <ProjectReference Include="..\SharpMUSH.Implementation\SharpMUSH.Implementation.csproj" />
    <PackageReference Include="MarkupString" Version="$(MarkupStringVersion)" />
    <PackageReference Include="MarkupString.Ansi" Version="$(MarkupStringVersion)" />
    <PackageReference Include="MarkupString.Html" Version="$(MarkupStringVersion)" />
  </ItemGroup>

</Project>
