# Copilot Setup Steps
# This file defines reusable setup steps for building and testing SharpMUSH with the latest .NET SDK
#
# Usage in a workflow:
#   - name: Setup Development Environment
#     uses: ./.github/copilot-setup-steps.yml

name: 'Setup SharpMUSH Development Environment'
description: 'Sets up the latest .NET SDK and prepares the environment for building and testing SharpMUSH'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET (Latest Stable)
      uses: actions/setup-dotnet@v4
      with:
        # Use 'x' to always get the latest stable version
        # This will automatically update to newer major versions as they're released
        dotnet-version: |
          8.x
          9.x
          10.x
        # Prefer the latest version if multiple are installed
        dotnet-quality: 'ga'

    - name: Restore dependencies
      shell: bash
      run: dotnet restore

    - name: Display .NET version
      shell: bash
      run: dotnet --version
