# Quick local build - copy pre-built binaries
FROM mcr.microsoft.com/dotnet/nightly/aspnet:11.0
WORKDIR /app
COPY SharpMUSH.ConnectionServer/bin/Release/net11.0/ ./
EXPOSE 4201 4202 4203
ENV ASPNETCORE_URLS=http://+:4202
ENTRYPOINT ["dotnet", "SharpMUSH.ConnectionServer.dll"]
