using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace SharpMUSH.Configuration.Generated;

using PropertyMetadata = (string PropertyName, string AttributeName);

[Generator]
public class ConfigMetadataGenerator : IIncrementalGenerator
{
	private const string SHARPATTRIBUTE = "SharpConfigAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var optionsProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (s, _) => s is RecordDeclarationSyntax { Identifier.Text: "SharpMUSHOptions" },
				transform: static (ctx, _) => (RecordDeclarationSyntax)ctx.Node)
			.Where(static m => m is not null);

		var compilation = context.CompilationProvider.Combine(optionsProvider.Collect());

		context.RegisterSourceOutput(compilation, Execute);
	}

	private static void Execute(SourceProductionContext spc,
		(Compilation Left, ImmutableArray<RecordDeclarationSyntax> Right) arg)
	{
		var compilation = arg.Left;
		var optionsClasses = arg.Right;

		if (optionsClasses.Length == 0) return;

		var optionsClass = optionsClasses[0];
		var semanticModel = compilation.GetSemanticModel(optionsClass.SyntaxTree);
		var optionsSymbol = semanticModel.GetDeclaredSymbol(optionsClass) as INamedTypeSymbol;

		if (optionsSymbol == null) return;

		var metadata = GetPropertyMetadata(optionsSymbol).ToImmutableArray();
		var metadataWithAttributes = GetPropertyMetadataWithAttributes(optionsSymbol)
			.Select(GeneratePropertyMetadataEntry)
			.ToImmutableArray();

		var str = $$"""
		            // <autogenerated/>
		            using System.Collections.Generic;
		            using System.Collections.Immutable;
		            using SharpMUSH.Configuration.Options;
		            
		            namespace SharpMUSH.Configuration.Generated;
		            
		            public static class ConfigMetadata
		            {
		                public static readonly ImmutableDictionary<string, string> PropertyToAttributeName = new Dictionary<string, string>
		                {
		                    {{string.Join(",\n            ", metadata.Select(m => $"{{ \"{m.PropertyName}\", \"{m.AttributeName}\" }}"))}}
		                }.ToImmutableDictionary();
		                
		                public static readonly ImmutableDictionary<string, string> AttributeToPropertyName = new Dictionary<string, string>
		                {
		                    {{string.Join(",\n            ", metadata.Select(m => $"{{ \"{m.AttributeName}\", \"{m.PropertyName}\" }}"))}}
		                }.ToImmutableDictionary();
		                
		                /// <summary>
		                /// Every configured property, in the order its category and then its record declares it.
		                /// The dictionaries below are unordered, and the config UI groups by first-seen order.
		                /// </summary>
		                public static readonly ImmutableArray<string> PropertyNames = [
		                    {{string.Join(",\n            ", metadata.Select(m => $"\"{m.PropertyName}\""))}}
		                ];
		                
		                public static readonly ImmutableDictionary<string, SharpConfigAttribute> PropertyMetadata = new Dictionary<string, SharpConfigAttribute>
		                {
		                    {{string.Join(",\n            ", metadataWithAttributes)}}
		                }.ToImmutableDictionary();
		            }
		            """;

		spc.AddSource("ConfigMetadata_Generated.g.cs", str);
	}

	private static IEnumerable<PropertyMetadata> GetPropertyMetadata(INamedTypeSymbol optionsSymbol)
	{
		foreach (var category in SelectCategoryProperties(optionsSymbol))
		{
			foreach (var prop in SelectConfigProperties(category))
			{
				var attr = prop.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == SHARPATTRIBUTE);
				var attrName = attr?.NamedArguments.FirstOrDefault(kv => kv.Key == "Name").Value.Value as string;
				yield return (prop.Name, attrName ?? prop.Name);
			}
		}
	}

	private static IEnumerable<(string CategoryName, IPropertySymbol Property, AttributeData Attribute)>
		GetPropertyMetadataWithAttributes(INamedTypeSymbol optionsSymbol)
	{
		foreach (var category in SelectCategoryProperties(optionsSymbol))
		{
			foreach (var prop in SelectConfigProperties(category))
			{
				var attr = prop.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == SHARPATTRIBUTE);
				if (attr is not null)
				{
					yield return (category.Name, prop, attr);
				}
			}
		}
	}

	private static string GeneratePropertyMetadataEntry(
		(string CategoryName, IPropertySymbol Property, AttributeData Attribute) metadata)
	{
		var prop = metadata.Property;
		var attr = metadata.Attribute;

		// The property that owns this category on SharpMUSHOptions ("Net"), not the record's type name
		// ("NetOptions"). That is the value every attribute declares, the value ConfigAccessor reports,
		// and the value SchemaBuilder derives, so all three agree.
		var category = metadata.CategoryName;

		var name = Named(attr, "Name") as string ?? "";
		var description = Named(attr, "Description") as string ?? "";
		var group = Named(attr, "Group") as string;
		var tooltip = Named(attr, "Tooltip") as string;
		var validationPattern = Named(attr, "ValidationPattern") as string;
		var order = Named(attr, "Order") is int o ? o : 0;

		return "{ \"" + prop.Name + "\", new SharpConfigAttribute { "
			+ $"Name = \"{Emit.Escape(name)}\", "
			+ $"Description = {Emit.Quote(description) ?? "\"\""}, "
			+ $"Category = \"{Emit.Escape(category)}\", "
			+ $"Group = {Emit.Quote(group) ?? "null"}, "
			+ $"Order = {order}, "
			+ $"Min = {Emit.Literal(Named(attr, "Min"))}, "
			+ $"Max = {Emit.Literal(Named(attr, "Max"))}, "
			+ $"Tooltip = {Emit.Quote(tooltip) ?? "null"}, "
			+ $"ValidationPattern = {Emit.Quote(validationPattern) ?? "null"}"
			+ " } }";
	}

	private static object? Named(AttributeData attr, string key)
		=> attr.NamedArguments.FirstOrDefault(kv => kv.Key == key).Value.Value;

	private static IEnumerable<IPropertySymbol> SelectCategoryProperties(INamedTypeSymbol optionsSymbol)
		=> optionsSymbol.GetMembers().OfType<IPropertySymbol>().Where(x => x.Name is not "EqualityContract");

	private static IEnumerable<IPropertySymbol> SelectConfigProperties(IPropertySymbol category)
	{
		return category.Type is INamedTypeSymbol categoryType
			? categoryType
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == SHARPATTRIBUTE))
			: [];
	}
}
