using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace SharpMUSH.Configuration.Generated;

[Generator]
public class ConfigAccessorGenerator : IIncrementalGenerator
{
	private const string SHARPATTRIBUTE = "SharpConfigAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var optionsProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (s, _) => s is RecordDeclarationSyntax { Identifier.Text: "SharpMUSHOptions" },
				transform: static (ctx, _) => (RecordDeclarationSyntax)ctx.Node)
			.Where(static m => m is not null);

		var compilation = context.CompilationProvider.Combine(optionsProvider.Collect());

		context.RegisterSourceOutput(compilation, Execute);
	}

	private static void Execute(SourceProductionContext spc,
		(Compilation Left, ImmutableArray<RecordDeclarationSyntax> Right) arg)
	{
		var compilation = arg.Left;
		var optionsClasses = arg.Right;

		if (optionsClasses.Length == 0) return;

		var optionsClass = optionsClasses[0];
		var semanticModel = compilation.GetSemanticModel(optionsClass.SyntaxTree);
		var optionsSymbol = semanticModel.GetDeclaredSymbol(optionsClass) as INamedTypeSymbol;

		if (optionsSymbol == null) return;

		var categories = SelectCategoryProperties(optionsSymbol).ToImmutableArray();
		var allProperties = categories
			.SelectMany(cat => SelectConfigProperties(cat).Select(prop => (Category: cat, Property: prop)))
			.ToImmutableArray();

		var categoriesList = string.Join(",\n            ", categories.Select(c => $"\"{c.Name}\""));

		var propertyAccessors = string.Join("\n\n        ", allProperties.Select(p => GeneratePropertyAccessor(p.Category, p.Property)));
		var propertySetters = string.Join("\n\n        ", allProperties.Select(p => GeneratePropertySetter(p.Category, p.Property)));

		var str = $$"""
		            // <autogenerated/>
		            #nullable enable
		            using System;
		            using System.Collections.Generic;
		            using System.Collections.Immutable;
		            using SharpMUSH.Configuration.Options;
		            
		            namespace SharpMUSH.Configuration.Generated;
		            
		            public static class ConfigAccessor
		            {
		                public static readonly ImmutableArray<string> Categories = [
		                    {{categoriesList}}
		                ];
		                
		                public static object? GetValue(SharpMUSHOptions options, string propertyName)
		                {
		                    return propertyName switch
		                    {
		                        {{string.Join("\n                ", allProperties.Select(p => $"\"{p.Property.Name}\" => options.{p.Category.Name}.{p.Property.Name},"))}}
		                        _ => null
		                    };
		                }
		                
		                public static bool TryGetValue(SharpMUSHOptions options, string propertyName, out object? value)
		                {
		                    value = GetValue(options, propertyName);
		                    return value != null;
		                }
		                
		                public static Type? GetPropertyType(string propertyName)
		                {
		                    return propertyName switch
		                    {
		                        {{string.Join("\n                ", allProperties.Select(p => $"\"{p.Property.Name}\" => typeof({GetTypeName(p.Property.Type)}),"))}}
		                        _ => null
		                    };
		                }
		                
		                public static string? GetCategoryForProperty(string propertyName)
		                {
		                    return propertyName switch
		                    {
		                        {{string.Join("\n                ", allProperties.Select(p => $"\"{p.Property.Name}\" => \"{p.Category.Name}\","))}}
		                        _ => null
		                    };
		                }
		            }
		            """;

		spc.AddSource("ConfigAccessor_Generated.g.cs", str);
	}

	private static string GeneratePropertyAccessor(IPropertySymbol category, IPropertySymbol property)
	{
		return $"// {category.Name}.{property.Name}";
	}

	private static string GeneratePropertySetter(IPropertySymbol category, IPropertySymbol property)
	{
		return $"// Set {category.Name}.{property.Name}";
	}

	private static string GetTypeName(ITypeSymbol type)
	{
		return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
	}

	private static IEnumerable<IPropertySymbol> SelectCategoryProperties(INamedTypeSymbol optionsSymbol)
		=> optionsSymbol.GetMembers().OfType<IPropertySymbol>().Where(x => x.Name is not "EqualityContract");

	private static IEnumerable<IPropertySymbol> SelectConfigProperties(IPropertySymbol category)
	{
		return category.Type is INamedTypeSymbol categoryType
			? categoryType
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == SHARPATTRIBUTE))
			: [];
	}
}
