// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpMUSH.DB;

#nullable disable

namespace SharpMUSH.Migrations
{
    [DbContext(typeof(MUSHContext))]
    [Migration("20220909195104_Tweak")]
    partial class Tweak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("BaseObjectBaseObject", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChildrenId", "ParentsId");

                    b.HasIndex("ParentsId");

                    b.ToTable("AncestorLink", (string)null);
                });

            modelBuilder.Entity("BaseObjectFlag", b =>
                {
                    b.Property<int>("FlagsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlagsId", "ThingsId");

                    b.HasIndex("ThingsId");

                    b.ToTable("ThingFlagsLink", (string)null);
                });

            modelBuilder.Entity("BaseObjectPermission", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermissionsId", "ThingsId");

                    b.HasIndex("ThingsId");

                    b.ToTable("BaseObjectPermission");
                });

            modelBuilder.Entity("CommandFlag", b =>
                {
                    b.Property<int>("CommandsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommandsId", "FlagsId");

                    b.HasIndex("FlagsId");

                    b.ToTable("CommandFlagsLink", (string)null);
                });

            modelBuilder.Entity("FlagPermission", b =>
                {
                    b.Property<int>("FlagsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlagsId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("FlagPermission");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.BaseObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GlobalTypeParent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("BaseObject");

                    b.HasDiscriminator<string>("type").HasValue("object");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectAttribute.Argument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CmdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CmdId");

                    b.ToTable("Argument");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectAttribute.Attrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThingId");

                    b.ToTable("Attributes");

                    b.HasDiscriminator<string>("type").HasValue("attribute");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectPerm.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectPerm.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.Exit", b =>
                {
                    b.HasBaseType("SharpMUSH.DB.Object.BaseObject");

                    b.HasDiscriminator().HasValue("exit");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.Player", b =>
                {
                    b.HasBaseType("SharpMUSH.DB.Object.BaseObject");

                    b.Property<bool>("Connected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EditMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Session")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("player");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.Room", b =>
                {
                    b.HasBaseType("SharpMUSH.DB.Object.BaseObject");

                    b.HasDiscriminator().HasValue("room");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.Thing", b =>
                {
                    b.HasBaseType("SharpMUSH.DB.Object.BaseObject");

                    b.HasDiscriminator().HasValue("thing");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectAttribute.Command", b =>
                {
                    b.HasBaseType("SharpMUSH.DB.ObjectAttribute.Attrib");

                    b.Property<bool>("Callable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cmd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Executable")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("command");
                });

            modelBuilder.Entity("BaseObjectBaseObject", b =>
                {
                    b.HasOne("SharpMUSH.DB.Object.BaseObject", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMUSH.DB.Object.BaseObject", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseObjectFlag", b =>
                {
                    b.HasOne("SharpMUSH.DB.ObjectPerm.Flag", null)
                        .WithMany()
                        .HasForeignKey("FlagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMUSH.DB.Object.BaseObject", null)
                        .WithMany()
                        .HasForeignKey("ThingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseObjectPermission", b =>
                {
                    b.HasOne("SharpMUSH.DB.ObjectPerm.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMUSH.DB.Object.BaseObject", null)
                        .WithMany()
                        .HasForeignKey("ThingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommandFlag", b =>
                {
                    b.HasOne("SharpMUSH.DB.ObjectAttribute.Command", null)
                        .WithMany()
                        .HasForeignKey("CommandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMUSH.DB.ObjectPerm.Flag", null)
                        .WithMany()
                        .HasForeignKey("FlagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlagPermission", b =>
                {
                    b.HasOne("SharpMUSH.DB.ObjectPerm.Flag", null)
                        .WithMany()
                        .HasForeignKey("FlagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMUSH.DB.ObjectPerm.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.BaseObject", b =>
                {
                    b.HasOne("SharpMUSH.DB.Object.BaseObject", "Location")
                        .WithMany("Contents")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpMUSH.DB.Object.Player", "Owner")
                        .WithMany("Owned")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectAttribute.Argument", b =>
                {
                    b.HasOne("SharpMUSH.DB.ObjectAttribute.Command", "Cmd")
                        .WithMany("Arguments")
                        .HasForeignKey("CmdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cmd");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectAttribute.Attrib", b =>
                {
                    b.HasOne("SharpMUSH.DB.Object.BaseObject", "Thing")
                        .WithMany("Attributes")
                        .HasForeignKey("ThingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thing");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.BaseObject", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("SharpMUSH.DB.Object.Player", b =>
                {
                    b.Navigation("Owned");
                });

            modelBuilder.Entity("SharpMUSH.DB.ObjectAttribute.Command", b =>
                {
                    b.Navigation("Arguments");
                });
#pragma warning restore 612, 618
        }
    }
}
