namespace SharpMUSH.Configuration.Options;

public record LimitOptions(
	uint MaxAliases = 3,
	uint MaxDbReference = 0,
	uint MaxAttrsPerObj = 2048,
	uint MaxLogins = 120,
	int MaxGuests = -1,
	uint MaxNamedQRegisters = 100,
	uint ConnectFailLimit = 10,
	uint IdleTimeout = 0,
	uint UnconnectedIdleTimeout = 5 * 60,
	uint KeepaliveTimeout = 5 * 60,
	uint WhisperLoudness = 100,
	uint StartingQuota = 20,
	uint StartingMoney = 150,
	uint Paycheck = 50,
	uint GuestPaycheck = 0,
	uint MaxPennies = 100000,
	uint MaxGuestPennies = 1000,
	uint MaxParents = 10,
	uint MailLimit = 300,
	uint MaxDepth = 10,
	uint PlayerQueueLimit = 100,
	uint QueueLoss = 63,
	uint QueueChunk = 3,
	uint FunctionRecursionLimit = 100,
	uint FunctionInvocationLimit = 1000000,
	uint CallLimit = 100,
	uint PlayerNameLen = 21,
	uint QueueEntryCpuTime = 10000,
	bool UseQuota = true,
	uint ChunkMigrate = 150
);