namespace SharpMUSH.Configuration.Options;

public record LimitOptions(
	uint MaxAliases,
	uint? MaxDbReference,
	uint MaxAttrsPerObj,
	uint MaxLogins,
	int MaxGuests,
	uint MaxNamedQRegisters,
	uint ConnectFailLimit,
	uint IdleTimeout,
	uint UnconnectedIdleTimeout,
	uint KeepaliveTimeout,
	uint WhisperLoudness,
	uint StartingQuota,
	uint StartingMoney,
	uint Paycheck,
	uint GuestPaycheck,
	uint MaxPennies,
	uint MaxGuestPennies,
	uint MaxParents,
	uint MailLimit,
	uint MaxDepth,
	uint PlayerQueueLimit,
	uint QueueLoss,
	uint QueueChunk,
	uint FunctionRecursionLimit,
	uint FunctionInvocationLimit,
	uint CallLimit,
	uint PlayerNameLen,
	uint QueueEntryCpuTime,
	bool UseQuota,
	uint ChunkMigrate
);