using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharpMUSH.Implementation.Generated;

[Generator]
public sealed class SharpMUSHIncrementalGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName("SharpMUSH.Library.Attributes.SharpFunctionAttribute",
				(node, _) => node is MethodDeclarationSyntax,
				(ctx, _) => (MethodDeclarationSyntax)ctx.TargetNode)
			.Where(x => x is not null);

		var compilation = context.CompilationProvider.Combine(provider.Collect());
		
		context.RegisterSourceOutput(compilation, Execute);
	}

	private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<MethodDeclarationSyntax> list) tuple)
	{
		var list = tuple.list;
		var nameList = list.Select(syntax => syntax.Identifier.Text).ToList();

		var code = $$"""
		             // Generated by SharpMUSHIncrementalGenerator
		             namespace SharpMUSH.Implementation.Generated; 

		             public static class GeneratedMarker 
		             { 
		             	{{string.Join("\n", nameList.Select(name => $"public const string {name} = \"{name}\";"))}}
		             	
		             	public static List<string> RegisteredFunctions = new List<string> 
		             	{ 
		             		{{string.Join(", ", nameList.Select(name => $"\t\t\"{name}\""))}}
		             	};
		             } 
		             """;
		
		context.AddSource("SharpMUSH.Implementation.Generated.One.g.cs", code);
	}
}