namespace SharpMUSH.Database.Seed;

/// <summary>
/// The built-in attribute entries (name + default flags), shared verbatim across all database providers.
/// Copied from <c>SharpMUSH.Database.SurrealDB/SurrealDatabase.Migration.cs</c>
/// (<c>CreateInitialAttributeEntries</c>). Includes the PennMUSH single-letter compatibility slots
/// (<c>VA</c>-<c>VZ</c>, <c>WA</c>-<c>WZ</c>, <c>XA</c>-<c>XZ</c>).
/// </summary>
public static class AttributeEntrySeed
{
	public static readonly (string Name, string[] DefaultFlags)[] Entries =
	[
		("AAHEAR", ["no_command","prefixmatch"]),
		("ABUY", ["no_command","prefixmatch"]),
		("ACLONE", ["no_command","prefixmatch"]),
		("ACONNECT", ["no_command","prefixmatch"]),
		("ADEATH", ["no_command","prefixmatch"]),
		("ADESCRIBE", ["no_command","prefixmatch"]),
		("ADESTROY", ["no_inherit","no_clone","wizard","prefixmatch"]),
		("ADISCONNECT", ["no_command","prefixmatch"]),
		("ADROP", ["no_command","prefixmatch"]),
		("AEFAIL", ["no_command","prefixmatch"]),
		("AENTER", ["no_command","prefixmatch"]),
		("AFAILURE", ["no_command","prefixmatch"]),
		("AFOLLOW", ["no_command","prefixmatch"]),
		("AGIVE", ["no_command","prefixmatch"]),
		("AHEAR", ["no_command","prefixmatch"]),
		("AIDESCRIBE", ["no_command","prefixmatch"]),
		("ALEAVE", ["no_command","prefixmatch"]),
		("ALFAIL", ["no_command","prefixmatch"]),
		("ALIAS", ["no_command","visual","prefixmatch"]),
		("AMAIL", ["wizard","prefixmatch"]),
		("AMHEAR", ["no_command","prefixmatch"]),
		("AMOVE", ["no_command","prefixmatch"]),
		("ANAME", ["no_command","prefixmatch"]),
		("APAYMENT", ["no_command","prefixmatch"]),
		("ARECEIVE", ["no_command","prefixmatch"]),
		("ASUCCESS", ["no_command","prefixmatch"]),
		("ATPORT", ["no_command","prefixmatch"]),
		("AUFAIL", ["no_command","prefixmatch"]),
		("AUNFOLLOW", ["no_command","prefixmatch"]),
		("AUSE", ["no_command","prefixmatch"]),
		("AWAY", ["no_command","prefixmatch"]),
		("AZENTER", ["no_command","prefixmatch"]),
		("AZLEAVE", ["no_command","prefixmatch"]),
		("BUY", ["no_command","prefixmatch"]),
		("CHANALIAS", ["no_command"]),
		("CHARGES", ["no_command","prefixmatch"]),
		("CHATFORMAT", ["no_command","prefixmatch"]),
		("COMMENT", ["no_command","no_clone","wizard","mortal_dark","prefixmatch"]),
		("CONFORMAT", ["no_command","prefixmatch"]),
		("COST", ["no_command","prefixmatch"]),
		("DEATH", ["no_command","prefixmatch"]),
		("DEBUGFORWARDLIST", ["no_command","no_inherit","prefixmatch"]),
		("DESCFORMAT", ["no_command","prefixmatch"]),
		("DESCRIBE", ["no_command","visual","prefixmatch","public","nearby"]),
		("DESTINATION", ["no_command"]),
		("DOING", ["no_command","no_inherit","visual","public"]),
		("DROP", ["no_command","prefixmatch"]),
		("EALIAS", ["no_command","prefixmatch"]),
		("EFAIL", ["no_command","prefixmatch"]),
		("ENTER", ["no_command","prefixmatch"]),
		("EXITFORMAT", ["no_command","prefixmatch"]),
		("EXITTO", ["no_command","prefixmatch"]),
		("FAILURE", ["no_command","prefixmatch"]),
		("FILTER", ["no_command","prefixmatch"]),
		("FOLLOW", ["no_command","prefixmatch"]),
		("FOLLOWERS", ["no_command","no_inherit","no_clone","wizard","prefixmatch"]),
		("FOLLOWING", ["no_command","no_inherit","no_clone","wizard","prefixmatch"]),
		("FORWARDLIST", ["no_command","no_inherit","prefixmatch"]),
		("GIVE", ["no_command","prefixmatch"]),
		("HAVEN", ["no_command","prefixmatch"]),
		("IDESCFORMAT", ["no_command","prefixmatch"]),
		("IDESCRIBE", ["no_command","prefixmatch"]),
		("IDLE", ["no_command","prefixmatch"]),
		("INFILTER", ["no_command","prefixmatch"]),
		("INPREFIX", ["no_command","prefixmatch"]),
		("INVFORMAT", ["no_command","prefixmatch"]),
		("LALIAS", ["no_command","prefixmatch"]),
		("LAST", ["no_clone","wizard","visual","locked","prefixmatch"]),
		("LASTFAILED", ["no_clone","wizard","locked","prefixmatch"]),
		("LASTIP", ["no_clone","wizard","locked","prefixmatch"]),
		("LASTLOGOUT", ["no_clone","wizard","locked","prefixmatch"]),
		("LASTPAGED", ["no_clone","wizard","locked","prefixmatch"]),
		("LASTSITE", ["no_clone","wizard","locked","prefixmatch"]),
		("LEAVE", ["no_command","prefixmatch"]),
		("LFAIL", ["no_command","prefixmatch"]),
		("LISTEN", ["no_command","prefixmatch"]),
		("MAILCURF", ["no_command","no_clone","wizard","locked","prefixmatch"]),
		("MAILFILTER", ["no_command","prefixmatch"]),
		("MAILFILTERS", ["no_command","no_clone","wizard","locked","prefixmatch"]),
		("MAILFOLDERS", ["no_command","no_clone","wizard","locked","prefixmatch"]),
		("MAILFORWARDLIST", ["no_command","prefixmatch"]),
		("MAILQUOTA", ["no_command","no_clone","wizard","locked"]),
		("MAILSIGNATURE", ["no_command","prefixmatch"]),
		("MONIKER", ["no_command","wizard","visual","locked"]),
		("MOVE", ["no_command","prefixmatch"]),
		("NAMEACCENT", ["no_command","visual","prefixmatch"]),
		("NAMEFORMAT", ["no_command","prefixmatch"]),
		("OBUY", ["no_command","prefixmatch"]),
		("ODEATH", ["no_command","prefixmatch"]),
		("ODESCRIBE", ["no_command","prefixmatch"]),
		("ODROP", ["no_command","prefixmatch"]),
		("OEFAIL", ["no_command","prefixmatch"]),
		("OENTER", ["no_command","prefixmatch"]),
		("OFAILURE", ["no_command","prefixmatch"]),
		("OFOLLOW", ["no_command","prefixmatch"]),
		("OGIVE", ["no_command","prefixmatch"]),
		("OIDESCRIBE", ["no_command","prefixmatch"]),
		("OLEAVE", ["no_command","prefixmatch"]),
		("OLFAIL", ["no_command","prefixmatch"]),
		("OMOVE", ["no_command","prefixmatch"]),
		("ONAME", ["no_command","prefixmatch"]),
		("OPAYMENT", ["no_command","prefixmatch"]),
		("ORECEIVE", ["no_command","prefixmatch"]),
		("OSUCCESS", ["no_command","prefixmatch"]),
		("OTPORT", ["no_command","prefixmatch"]),
		("OUFAIL", ["no_command","prefixmatch"]),
		("OUNFOLLOW", ["no_command","prefixmatch"]),
		("OUSE", ["no_command","prefixmatch"]),
		("OUTPAGEFORMAT", ["no_command","prefixmatch"]),
		("OXENTER", ["no_command","prefixmatch"]),
		("OXLEAVE", ["no_command","prefixmatch"]),
		("OXMOVE", ["no_command","prefixmatch"]),
		("OXTPORT", ["no_command","prefixmatch"]),
		("OZENTER", ["no_command","prefixmatch"]),
		("OZLEAVE", ["no_command","prefixmatch"]),
		("PAGEFORMAT", ["no_command","prefixmatch"]),
		("PAYMENT", ["no_command","prefixmatch"]),
		("PREFIX", ["no_command","prefixmatch"]),
		("PRICELIST", ["no_command","prefixmatch"]),
		("QUEUE", ["no_inherit","no_clone","wizard"]),
		("RECEIVE", ["no_command","prefixmatch"]),
		("REGISTERED_EMAIL", ["no_inherit","no_clone","wizard","locked"]),
		("RQUOTA", ["mortal_dark","locked"]),
		("RUNOUT", ["no_command","prefixmatch"]),
		("SEMAPHORE", ["no_inherit","no_clone","locked"]),
		("SEX", ["no_command","visual","prefixmatch"]),
		("SPEECHMOD", ["no_command","prefixmatch"]),
		("STARTUP", ["no_command","prefixmatch"]),
		("SUCCESS", ["no_command","prefixmatch"]),
		("TFPREFIX", ["no_command","no_inherit","no_clone","prefixmatch"]),
		("TPORT", ["no_command","prefixmatch"]),
		("TZ", ["no_command","visual"]),
		("UFAIL", ["no_command","prefixmatch"]),
		("UNFOLLOW", ["no_command","prefixmatch"]),
		("USE", ["no_command","prefixmatch"]),
		("VA", []), ("VB", []), ("VC", []), ("VD", []), ("VE", []), ("VF", []),
		("VG", []), ("VH", []), ("VI", []), ("VJ", []), ("VK", []), ("VL", []),
		("VM", []), ("VN", []), ("VO", []), ("VP", []), ("VQ", []), ("VR", []),
		("VRML_URL", ["no_command","prefixmatch"]),
		("VS", []), ("VT", []), ("VU", []), ("VV", []), ("VW", []), ("VX", []),
		("VY", []), ("VZ", []),
		("WA", []), ("WB", []), ("WC", []), ("WD", []), ("WE", []), ("WF", []),
		("WG", []), ("WH", []), ("WI", []), ("WJ", []), ("WK", []), ("WL", []),
		("WM", []), ("WN", []), ("WO", []), ("WP", []), ("WQ", []), ("WR", []),
		("WS", []), ("WT", []), ("WU", []), ("WV", []), ("WW", []), ("WX", []),
		("WY", []), ("WZ", []),
		("XA", []), ("XB", []), ("XC", []), ("XD", []), ("XE", []), ("XF", []),
		("XG", []), ("XH", []), ("XI", []), ("XJ", []), ("XK", []), ("XL", []),
		("XM", []), ("XN", []), ("XO", []), ("XP", []), ("XQ", []), ("XR", []),
		("XS", []), ("XT", []), ("XU", []), ("XV", []), ("XW", []), ("XX", []),
		("XY", []), ("XZ", []),
		("ZENTER", ["no_command","prefixmatch"]),
		("_", ["veiled"]),
	];
}
